hmcts/idam-slack-help-bot

config/default.yaml, package.json, src/service/persistence.js, src/service/persistence.test.js
Remove CCD specific Jira fields
```
[ ] Yes
[x] No
```
=> Remove CCD specific Jira fields

app.js, src/util/blockHelper.js, src/util/blockhelper.test.js
- Added random number (maybe should change this to something more unique) to 'assign_help_request_to_user' action id to invalidate previous form
- Updated initial user of 'assign_help_request_to_user' field to achieve 'take it' user being promoted here
- Added regex action matching to catch now changing action id for 'assign_help_request_to_user'
```
[ ] Yes
[x] No
```
=> fix for issue of assigned user not applying

app.js, src/service/helpRequestManager.js, src/service/persistence.js, src/workflow/supportRequestStep.js
Add IDAM support request workflow step from app
```
[ ] Yes
[x] No
```
=> Add IDAM support request workflow step from app

app.js, src/messages.js, src/service/helpRequestManager.js, src/service/jiraMessages.js, src/service/persistence.js, src/util/helpers.js, src/workflow/bugReportStep.js
Create IDAM bug reporting workflow step
```
[ ] Yes
[x] No
```
=> Create IDAM bug reporting workflow step

.github/workflows/build.yml
Add github workflows action to build slack bot
```
[ ] Yes
[x] No
```
=> Add github workflows action to build slack bot

README.md
Test flux config is working
```
[ ] Yes
[x] No
```
=> Withdraw button

app.js, config/custom-environment-variables.yaml, config/default.yaml, env.template.txt, src/messages.js, src/service/helpRequestManager.js, src/service/jiraTicketTypes.js, src/service/persistence.js, src/util/helpers.test.js, src/workflow/bugReportStep.js, src/workflow/newOidcServiceStep.js, src/workflow/newUserRoleStep.js
Add support for OIDC service and user role requests
```
[ ] Yes
[x] No
```
=> Add support for OIDC service and user role requests

src/service/helpRequestManager.js
Add logging to test slack bot in live
```
[ ] Yes
[x] No
```
=> Add logging to test slack bot in live

src/service/helpRequestManager.js
Remove temporary logging from slack bot
```
[ ] Yes
[x] No
```
=> Remove temporary logging from slack bot

app.js, src/service/helpRequestManager.js, src/util/helpers.js
Fix issue with comments from slack not written out to Jira
```
[ ] Yes
[x] No
```
=> Fix issue with comments from slack not written out to Jira

app.js, src/messages.js, src/service/jiraMessages.js, src/service/jiraTicketTypes.js, src/service/persistence.js, src/workflow/bugReportStep.js
- Retrieve Jira transition ID programmatically by reading relevant transition name from Jira.
- Fixed issue where the text 'Status' not in bold after the issue has been withdrawn.
- Added the field 'Affected roles' to bug issue type
- Removing emoji for all issue types
```
[ ] Yes
[x] No
```
=> Update IDAM slack bot following review

app.js, src/workflow/bugReportStep.js, src/workflow/newOidcServiceStep.js, src/workflow/newUserRoleStep.js, src/workflow/supportRequestStep.js
- Fix issue where comments from slack not written to Jira
- Add N/A test to black fields on slack 
```
[ ] Yes
[x] No
```
=> Fix issue where comments from slack not written to Jira

app.js, src/service/helpRequestManager.js, src/service/persistence.js
Add logging for debugging issue where comments not working in live
```
[ ] Yes
[x] No
```
=> Add logging for debugging

app.js, config/custom-environment-variables.yaml, config/default.yaml, package-lock.json, package.json, src/service/Service.js, src/service/serviceStatus.js, src/workflow/getServiceStatusStep.js
https://tools.hmcts.net/jira/browse/SIDM-7182
- Added service monitoring capability which watches idam-web-public health endpoint for changes in service health for itself and API.
- Service monitoring will check each service every 15s for changes, and will keep track of 'last seen' time 
- Added new workflow step `getServiceStatusWorkflowStep` which pretty formats current status of services
```
[ ] Yes
[x] No
```
=> SIDM-7182 - Added environment monitoring

src/workflow/getServiceStatusStep.js
=> SIDM-7182 - Bug fix?

package-lock.json, package.json, src/service/serviceStatus.js
https://tools.hmcts.net/jira/browse/SIDM-7182
- Added retries to env monitoring. Will try again 3 times (with a 1.5s pause).
```
[ ] Yes
[x] No
```
=> SIDM-7182 - Added monitoring retries

src/service/Service.js, src/service/serviceStatus.js, src/workflow/getServiceStatusStep.js
- Fix for issue where each retry could wait up to 300s on a dead connection, causing function to not progress
```
[ ] Yes
[x] No
```
=> Fix for env status issues where waiting for 300s for response

Dockerfile
- Updated to node 16
```
[ ] Yes
[] No
```
=> Update to node 16

src/service/Service.js, src/service/serviceStatus.js, src/workflow/getServiceStatusStep.js
https://tools.hmcts.net/jira/browse/SIDM-8209
- Added user-dashboard to the service status check
- Contact idam-api directly rather than relying on status through web-public's health endpoint
```
[ ] Yes
[x] No
```
=> SIDM-8209 - Add user-dashboard to service status check

src/service/serviceStatus.js
- Add more info the failure message when failing to reach a service
```
[ ] Yes
[x] No
```
=> Add more info to failure logs when pinging services

renovate.json
https://tools.hmcts.net/jira/browse/SIDM-8846
Automerge Renovate PRs
=> Automerge Renovate PRs

src/messages.js, src/workflow/supportRequestStep.js
=> Amended labels in IDAM Support Request workflow.

src/service/serviceStatus.js
https://tools.hmcts.net/jira/browse/SIDM-9017
Just some debug log.
=> Add debug logs

src/workflow/getServiceStatusStep.js
N/A
Change text in Get Service Status workflow.
=> Update text in getServiceStatus

src/workflow/bugReportStep.js
=> Amended text.

app.js
=> Disabled support request workflow.

app.js
=> Enable support request workflow.

src/messages.js
=> service field is mandatory.

app.js, src/workflow/supportRequestStep.js
=> Disabled createSupportRequestStep.

src/messages.js
=> Fixed form schema issues.

src/messages.js, src/service/helpRequestManager.js
=> Added support form validation and logging

app.js, src/messages.js, src/workflow/newSupportRequestStep.js, src/workflow/supportRequestStep.js
=> Added workflow to handle new support request announcement and Reverted validation changes.

app.js, src/messages.js
=> Added shortcut, form and backend integration for "Report IDAM bug".

app.js, src/messages.js, src/workflow/newBugReportStep.js, src/workflow/newUserRoleStep.js
=> Added announcement workflows for "Report IDAM bug" and "New IDAM user role"

app.js, src/messages.js, src/workflow/newRoleRequestStep.js
=> Added announcement workflow for "New IDAM user role".

src/service/helpRequestManager.js
=> Fixed logging
